apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: restaurant
  labels:
    app: booking-service
    # This label is matched by ServiceMonitor
    release: prometheus
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
